import type { Pool, PoolClient } from 'pg'

type Db = Pool | PoolClient

export async function ensureCollectionFilesTable(db: Db): Promise<void> {
  await db.query(`
    CREATE TABLE IF NOT EXISTS collection_files (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
      filename TEXT PRIMARY KEY,
      filesize BIGINT NOT NULL
    );

    CREATE INDEX IF NOT EXISTS collection_files_filename_lower_idx
    ON collection_files((lower(filename)));

    CREATE INDEX IF NOT EXISTS collection_files_search_idx
    ON collection_files USING GIN (to_tsvector('simple', filename));
  `)

  await db.query(`
    ALTER TABLE collection_files
    ADD COLUMN IF NOT EXISTS id BIGINT
  `)

  await db.query(`
    DO $$
    BEGIN
      IF NOT EXISTS (SELECT 1 FROM pg_class WHERE relname = 'collection_files_id_seq') THEN
        CREATE SEQUENCE collection_files_id_seq OWNED BY collection_files.id;
      END IF;
    END
    $$;
    ALTER TABLE collection_files ALTER COLUMN id SET DEFAULT nextval('collection_files_id_seq');
    UPDATE collection_files SET id = nextval('collection_files_id_seq') WHERE id IS NULL;
    CREATE UNIQUE INDEX IF NOT EXISTS collection_files_id_idx ON collection_files(id);
  `)
}
